# Generated by Django 3.2 on 2022-12-15 21:30

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
