# Generated by Django 3.2 on 2022-12-17 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_auto_20221217_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='like',
        ),
    ]
